packaging_format = 2

id = "matomo"
name = "Matomo"
description.en = "Analytics platform for measuring Web statistics"
description.fr = "Plateforme d'analyse de mesure de statistiques Web"

version = "4.16.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-or-later"
website = "https://matomo.org"
demo = "https://demo.matomo.org"
admindoc = "https://matomo.org/docs"
code = "https://github.com/matomo-org/matomo"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/matomo"

    [install.init_main_permission]
    help.en = "If visitors enabled, Matomo will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si visiteurs est cochée, Matomo sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://builds.matomo.org/matomo-4.16.0.tar.gz"
        sha256 = "385653e35f795935b0d97340c8688d8b15ba85234a0b72320696b990cf4f0959"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-curl, php8.2-gd, php8.2-cli, php8.2-mysql, php8.2-xml, php8.2-mbstring"

    [resources.database]
    type = "mysql"
    