packaging_format = 2

id = "matomo"
name = "Matomo"
description.en = "Open source analytics platform for measuring Web statistics"
description.fr = "Plateforme d'analyse open source de mesure de statistiques Web"

version = "4.15.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-or-later"
website = "https://matomo.org"
demo = "https://demo.matomo.org"
admindoc = "https://matomo.org/docs"
code = "https://github.com/matomo-org/matomo"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/matomo"

    [install.init_main_permission]
    help.en = "If enabled, Matomo will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Matomo sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://builds.matomo.org/matomo-4.15.0.tar.gz"
        sha256 = "619b2ef500e1c50f4ccee2e094ddfa0928cf8e76fe40b787483c1d11ee69978e"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.2-curl php8.2-gd php8.2-cli php8.2-mysql php8.2-xml php8.2-mbstring"

    [resources.database]
    type = "mysql"
    